[workspace]
channels = ["conda-forge"]
name = "GraphTM-exp"
platforms = ["linux-64"]

[tasks]

[system-requirements]
cuda = "12"

[dependencies]
cuda = ">=12.9.1,<13"
python = ">=3.11,<3.12"
pandas = ">=2.3.3,<3"
nltk = ">=3.9.2,<4"
matplotlib = ">=3.10.7,<4"
scikit-image = ">=0.25.2,<0.26"
scikit-learn = ">=1.7.2,<2"
tqdm = ">=4.67.1,<5"
seaborn = ">=0.13.2,<0.14"
pytorch-gpu = ">=2.8.0,<3"
torch-geometric = ">=2.6.1,<3"
numpy = ">=2.3.3,<3"
ipdb = ">=0.13.13,<0.14"
ipython = ">=9.6.0,<10"
jupyterlab = ">=4.4.10,<5"
numba = ">=0.62.1,<0.63"
pyarrow = ">=21.0.0,<22"
bottleneck = ">=1.6.0,<2"
kagglehub = ">=0.3.8,<0.4"
datasets = ">=4.2.0,<5"
py-opencv = ">=4.12.0,<5"
rdkit = ">=2025.9.1,<2026"
cairosvg = ">=2.8.2,<3"
ipywidgets = ">=8.1.7,<9"
pandas-stubs = ">=2.3.2.250926,<3"
pygraphviz = ">=1.14,<2"
netgraph = ">=4.13.2,<5"
py-xgboost = ">=3.0.5,<4"
chembl_structure_pipeline = ">=1.2.2,<2"
nvidia-ml-py = ">=13.580.82,<14"

[pypi-dependencies]
graphtm_exp = { path = ".", editable = true }
pycuda = ">=2025.1.2, <2026"
tensorflow = ">=2.20.0, <3"
graphtsetlinmachine = { git = "https://github.com/cair/GraphTsetlinMachine.git" }
pharmacophore-toolkit = "*"
pysparsecoalescedtsetlinmachinecuda = { git = "https://github.com/cair/PySparseCoalescedTsetlinMachineCUDA.git" }
pyjoules = { version = ">=0.5.1, <0.6" }
tmu = { git = "https://github.com/cair/tmu.git" }
